#!/bin/sh

# Rename SVGZ images

# rename -e 's/\.svgz/.svg.gz/' content/**/*.svgz

message() {
        msg="$*"
        printf "\033[0;32m${msg}\033[0m\n"
}

message "Rename SVGZ files to .SVG.GZ"

find content -type f -name '*.svgz' -print0 | xargs -0 rename -e 's/\.svgz/.svg.gz/'

message "Update links in Markdown files" 

find content -type f -name '_index.md' -print0 | xargs -0 sed -i 's/\.svgz)/.svg.gz)/g' 
